export const POSTS_DATA_REQUEST ="POSTS_DATA_REQUEST";
export const POSTS_DATA_SUCCESS ="POSTS_DATA_SUCCESS";
export const POSTS_DATA_FAILED ="POSTS_DATA_FAILED";

export const USERSPOST_DATA_REQUEST ="USERSPOST_DATA_REQUEST";
export const USERSPOST_DATA_SUCCESS ="USERSPOST_DATA_SUCCESS";
export const USERSPOST_DATA_FAILED ="USERSPOST_DATA_FAILED";

export const USERSCOMMENTS_DATA_REQUEST ="USERSCOMMENTS_DATA_REQUEST";
export const USERSCOMMENTS_DATA_SUCCESS ="USERSCOMMENTS_DATA_SUCCESS";
export const USERSCOMMENTS_DATA_FAILED ="USERSCOMMENTS_DATA_FAILED";
